apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "danswer-stack.fullname" . }}
  labels:
    {{- include "danswer-stack.labels" . | nindent 4 }}
data:
  INTERNAL_URL: "{{ include "danswer-stack.fullname" . }}-api:80"
  POSTGRES_HOST: {{ .Release.Name }}-postgres
  VESPA_HOST: "document-index-service"
{{- range $key, $value := .Values.configMap }}
  {{ $key }}: "{{ $value }}"
{{- end }}