apiVersion: v1
kind: Secret
metadata:
  name: danswer-secrets
type: Opaque
data:
  postgres_user: {{ .Values.danswerSecrets.postgres_user | b64enc }}
  postgres_password: {{ .Values.danswerSecrets.postgres_password | b64enc }}
  # Encode other secrets similar