apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.danswerBackend.deployment.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.danswerBackend.deployment.replicas }}
  selector:
    matchLabels:
      app: background
  template:
    metadata:
      labels:
        app: background
    spec:
      containers:
      - name: background
        image: {{ .Values.danswerBackend.deployment.image }}
        imagePullPolicy: {{ .Values.danswerBackend.deployment.imagePullPolicy }}
        command: {{ .Values.danswerBackend.deployment.command }}
        envFrom:
        - configMapRef:
            name: {{ .Values.danswerBackend.deployment.envFromConfigMap }}
        volumeMounts:
          {{- range .Values.danswerBackend.deployment.volumeMounts }}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
          {{- end }}
        resources:
          requests:
            memory: "{{ .Values.danswerBackend.deployment.resources.requests.memory }}"
            cpu: "{{ .Values.danswerBackend.deployment.resources.requests.cpu }}"
          limits:
            memory: "{{ .Values.danswerBackend.deployment.resources.limits.memory }}"
            cpu: "{{ .Values.danswerBackend.deployment.resources.limits.cpu }}"

      volumes:
        {{- range .Values.danswerBackend.deployment.volumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .persistentVolumeClaim.claimName }}
        {{- end }}