apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nginx.deployment.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.nginx.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.nginx.deployment.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.nginx.deployment.app }}
    spec:
      containers:
      - name: nginx
        image: {{ .Values.nginx.deployment.image }}
        imagePullPolicy: {{ .Values.nginx.deployment.imagePullPolicy }}
        command: 
         {{- range .Values.nginx.deployment.command }}
         - {{ . }}
         {{- end }}
        ports:
          - containerPort: {{ .Values.nginx.deployment.port }}
      env:
        - name: {{ .Values.nginx.deployment.env.name }}
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.nginx.deployment.env.ConfigMapKeyReference.name }}
              key: {{ .Values.nginx.deployment.env.ConfigMapKeyReference.key }}
      volumeMounts:
      {{- range .Values.nginx.deployment.volumeMounts }}
      - name: {{ .name }}
        mountPath: {{ .mountPath }}
      {{- end }}
      volumes:
      {{- range .Values.nginx.deployment.volumes }}
      - name: {{ .name }}
        configMap:
          name: {{ .configMapName }}
      {{- end }}