apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.service.name }}
spec:
  selector:
    app: {{ .Values.postgresql.statefulSet.app }}
  ports:
    {{- range .Values.postgresql.service.ports }}
    - protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
  clusterIP: None  
