apiVersion: v1
kind: Service
metadata:
  name: api-server-service
spec:
  selector:
    app: api-server
  ports:
    - name: api-server-port
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: api-server
        image: danswer/danswer-backend:latest
        imagePullPolicy: IfNotPresent
        command:
          - "/bin/sh"
          - "-c"
          - |
            alembic upgrade head &&
            echo "Starting Danswer Api Server" &&
            uvicorn danswer.main:app --host 0.0.0.0 --port 8080
        ports:
        - containerPort: 8080
        env:
        - name: WEB_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: WEB_DOMAIN
        - name: AUTH_TYPE
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: AUTH_TYPE
        - name: POSTGRES_HOST
          value: relational-db-service
        - name: GOOGLE_OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: danswer-secrets
              key: google_oauth_client_id
        - name: GOOGLE_OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: danswer-secrets
              key: google_oauth_client_secret
        - name: INTERNAL_MODEL_VERSION
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: INTERNAL_MODEL_VERSION
        - name: GEN_AI_MODEL_VERSION
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: GEN_AI_MODEL_VERSION
        - name: GEN_AI_API_KEY
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: GEN_AI_API_KEY
        - name: GEN_AI_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: GEN_AI_ENDPOINT
        - name: GEN_AI_HOST_TYPE
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: GEN_AI_HOST_TYPE
        - name: GEN_AI_MODEL_PROVIDER
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: GEN_AI_MODEL_PROVIDER
        - name: NUM_DOCUMENT_TOKENS_FED_TO_GENERATIVE_MODEL
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: NUM_DOCUMENT_TOKENS_FED_TO_GENERATIVE_MODEL
        - name: VESPA_HOST
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: VESPA_HOST
        - name: QA_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: QA_TIMEOUT
        - name: VALID_EMAIL_DOMAINS
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: VALID_EMAIL_DOMAINS
        - name: DISABLE_GENERATIVE_AI
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: DISABLE_GENERATIVE_AI
        - name: API_BASE_OPENAI
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: API_BASE_OPENAI
        - name: API_TYPE_OPENAI
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: API_TYPE_OPENAI
        - name: API_VERSION_OPENAI
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: API_VERSION_OPENAI
        - name: AZURE_DEPLOYMENT_ID
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: AZURE_DEPLOYMENT_ID
        volumeMounts:
        - name: dynamic-storage
          mountPath: /home/storage
        - name: file-connector-storage
          mountPath: /home/file_connector_storage
      volumes:
      - name: dynamic-storage
        persistentVolumeClaim:
          claimName: dynamic-pvc
      - name: file-connector-storage
        persistentVolumeClaim:
          claimName: file-connector-pvc
