apiVersion: v1
kind: Service
metadata:
  name: {{ include "danswer.fullname" . }}-api-server
spec:
  selector:
    app: api-server
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.apiServer.service.port }}
      targetPort: {{ .Values.apiServer.containerPort }}
  type: {{ .Values.apiServer.service.type }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "danswer.fullname" . }}-api-server
spec:
  replicas: {{ .Values.apiServer.replicaCount }}
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: api-server
        image: "{{ .Values.apiServer.image.repository }}:{{ .Values.apiServer.image.tag }}"
        imagePullPolicy: {{ .Values.apiServer.image.pullPolicy }}
        command:
          - "/bin/sh"
          - "-c"
          - |
            alembic upgrade head &&
            echo "Starting Danswer Api Server" &&
            uvicorn danswer.main:app --host 0.0.0.0 --port 8080
        ports:
        - containerPort: {{ .Values.apiServer.containerPort }}
        # There are some extra values since this is shared between services
        # There are no conflicts though, extra env variables are simply ignored
        envFrom:
        - configMapRef:
            name: env-configmap
        volumeMounts:
        - name: dynamic-storage
          mountPath: /home/storage
        - name: file-connector-storage
          mountPath: /home/file_connector_storage
      volumes:
      - name: dynamic-storage
        persistentVolumeClaim:
          claimName: dynamic-pvc
      - name: file-connector-storage
        persistentVolumeClaim:
          claimName: file-connector-pvc
