apiVersion: apps/v1
kind: Deployment
metadata:
  name: background-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: background
  template:
    metadata:
      labels:
        app: background
    spec:
      containers:
      - name: background
        image: danswer/danswer-backend:latest
        imagePullPolicy: IfNotPresent
        command: ["/usr/bin/supervisord"]
        env:
        - name: WEB_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: WEB_DOMAIN
        - name: GEN_AI_MODEL_VERSION
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: GEN_AI_MODEL_VERSION
        - name: GEN_AI_MODEL_PROVIDER
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: GEN_AI_MODEL_PROVIDER
        - name: API_BASE_OPENAI
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: API_BASE_OPENAI
        - name: API_TYPE_OPENAI
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: API_TYPE_OPENAI
        - name: API_VERSION_OPENAI
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: API_VERSION_OPENAI
        - name: AZURE_DEPLOYMENT_ID
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: AZURE_DEPLOYMENT_ID
        - name: DANSWER_BOT_SLACK_APP_TOKEN
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: DANSWER_BOT_SLACK_APP_TOKEN
        - name: DANSWER_BOT_SLACK_BOT_TOKEN
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: DANSWER_BOT_SLACK_BOT_TOKEN
        - name: POSTGRES_HOST
          value: relational-db-service
        - name: VESPA_HOST
          value: document-index-service
        volumeMounts:
        - name: dynamic-storage
          mountPath: /home/storage
        - name: file-connector-storage
          mountPath: /home/file_connector_storage
      volumes:
      - name: dynamic-storage
        persistentVolumeClaim:
          claimName: dynamic-pvc
      - name: file-connector-storage
        persistentVolumeClaim:
          claimName: file-connector-pvc
