apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "danswer.fullname" . }}-background
spec:
  replicas: {{ .Values.background.replicaCount }}
  selector:
    matchLabels:
      app: background
  template:
    metadata:
      labels:
        app: background
    spec:
      containers:
      - name: background
        image: "{{ .Values.background.image.repository }}:{{ .Values.background.image.tag }}"
        imagePullPolicy: {{ .Values.background.image.pullPolicy }}
        command: ["/usr/bin/supervisord"]
        # There are some extra values since this is shared between services
        # There are no conflicts though, extra env variables are simply ignored
        envFrom:
        - configMapRef:
            name: {{ include "danswer.configmapName" . }}
        volumeMounts:
        - name: dynamic-storage
          mountPath: /home/storage
        - name: file-connector-storage
          mountPath: /home/file_connector_storage
      volumes:
      - name: dynamic-storage
        persistentVolumeClaim:
          claimName: {{ .Values.dynamicStorage.claimName }}
      - name: file-connector-storage
        persistentVolumeClaim:
          claimName: {{ .Values.fileConnectorStorage.claimName }}
