apiVersion: v1
kind: Service
metadata:
  name: {{ include "danswer.fullname" . }}-nginx
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.service.port }}
    - name: danswer
      protocol: TCP
      port: 3000
      targetPort: 80
  type: {{ .Values.nginx.service.type }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "danswer.fullname" . }}-nginx
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
        ports:
        - containerPort: 80
        env:
        - name: DOMAIN
          valueFrom:
            configMapKeyRef:
              name: {{ include "danswer.configmapName" . }}
              key: DOMAIN
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
        command:
        - /bin/sh
        - -c
        - |
          while :; do sleep 6h & wait $$!; nginx -s reload; done & nginx -g "daemon off;"
      volumes:
      - name: nginx-conf
        configMap:
          name: {{ include "danswer.configmapName" . }}
