apiVersion: v1
kind: Service
metadata:
  name: {{ include "danswer.fullname" . }}-vespa
spec:
  selector:
    app: vespa
  ports:
    - name: vespa-tenant-port
      protocol: TCP
      port: {{ .Values.vespa.service.port }}
      targetPort: {{ .Values.vespa.service.targetPort }}
    - name: vespa-port
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vespa
  labels:
    app: vespa
spec:
  replicas: {{ .Values.vespa.replicaCount }}
  serviceName: vespa
  selector:
    matchLabels:
      app: vespa
  template:
    metadata:
      labels:
        app: vespa
    spec:
      containers:
      - name: vespa
        image: "{{ .Values.vespa.image.repository }}:{{ .Values.vespa.image.tag }}"
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
          runAsUser: 0
        ports:
        - containerPort: {{ .Values.vespa.containerPort }}
        - containerPort: {{ .Values.vespa.secondContainerPort }}
        readinessProbe:
          httpGet:
            path: /state/v1/health
            port: 19071
            scheme: HTTP
        volumeMounts:
        - name: vespa-storage
          mountPath: /opt/vespa/var/
  volumeClaimTemplates:
  - metadata:
      name: vespa-storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          # Adjust the storage request size as needed.
          storage: {{ .Values.vespa.persistence.size }}
