apiVersion: v1
kind: Service
metadata:
  name: web-server-service
spec:
  selector:
    app: web-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web-server
        image: danswer/danswer-web-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        args:
        env:
        - name: AUTH_TYPE
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: AUTH_TYPE
        - name: INTERNAL_URL
          valueFrom:
              configMapKeyRef:
                name: env-configmap
                key: INTERNAL_URL
