apiVersion: v1
kind: Service
metadata:
  name: {{ include "danswer.fullname" . }}-web-server
spec:
  selector:
    app: web-server
  ports:
    - protocol: TCP
      port: {{ .Values.webServer.service.port }}
      targetPort: {{ .Values.webServer.containerPort }}
  type: {{ .Values.webServer.service.type }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "danswer.fullname" . }}-web-server
spec:
  replicas: {{ .Values.webServer.replicaCount }}
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web-server
        image: "{{ .Values.webServer.image.repository }}:{{ .Values.webServer.image.tag }}"
        imagePullPolicy: {{ .Values.webServer.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.webServer.containerPort }}
        # There are some extra values since this is shared between services
        # There are no conflicts though, extra env variables are simply ignored
        envFrom:
        - configMapRef:
            name: {{ include "danswer.configmapName" . }}
