name: Python Checks

on:
  pull_request:
    branches: [ main ]  # replace with your target branch

jobs:
  mypy-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd backend
        pip install -r requirements/default.txt
        pip install -r requirements/dev.txt

    - name: Run MyPy
      run: |
        cd backend
        mypy .

    - name: Check import order with reorder-python-imports
      run: |
        cd backend
        find . -name "*.py" | xargs reorder-python-imports --py311-plus

    - name: Check code formatting with Black
      run: |
        cd backend
        black --check .
